### ISSUE TITLE
Refactor - Index Components

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/v13-bears-team-04#58]
All the components in the right column on the `/` page need to be refactored/styled correctly.

`HomeBox` is completed and can be used an example.

Components that need updating:
- `GrowingCommunities` // taken 
- `TrendingCommunity` // taken
- `Recent Posts` // taken
- `FooterBox` // taken - this one is sitting in PRs

Please comment which you're working on and I'll cross it out above.

**Hint:**
Each components parent element should have the following CSS:
```css
.parent-element-name {
  width: 100%;
  margin-bottom: 16px;
  border-radius: 0.5rem;
  background-color: $white;
}
```
